// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

dotenv.config({ path: ".env.migrate.local", override: true });
dotenv.config({ path: ".env.local" });
dotenv.config({ path: ".env" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Use a direct connection for Prisma CLI workflows when available.
    url: process.env["TEST_DATABASE_URL"] ?? process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
