import Link from "next/link"
import { ArrowRight, BookOpen, Clock3, Code2 } from "lucide-react"
import { Navbar } from "@/components/navbar"
import { Footer } from "@/components/footer"
import { prisma } from "@/lib/prisma"

export const dynamic = "force-dynamic"

export default async function FreeLearningPage() {
  const tutorials = await prisma.tutorial.findMany({ where: { status: "published" }, include: { sections: { include: { _count: { select: { lessons: { where: { isPublished: true } } } } } } }, orderBy: { publishedAt: "desc" } })
  return <div className="min-h-screen bg-background"><Navbar /><main className="pt-16"><section className="border-b border-border bg-gradient-to-br from-primary/10 via-background to-secondary/10"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24"><p className="text-sm font-semibold uppercase tracking-wider text-primary">Dzidza Free Learning</p><h1 className="mt-3 max-w-3xl text-4xl font-semibold tracking-tight sm:text-5xl">Practical skills, explained one clear step at a time.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-muted-foreground">Read original tutorials, practise with examples and exercises, and track your progress when you sign in. Every lesson is free.</p></div></section><section className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><div className="mb-7"><h2 className="text-2xl font-semibold">Start learning</h2><p className="mt-2 text-muted-foreground">More tutorials are being prepared by Dzidza Hub content managers.</p></div>{tutorials.length ? <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{tutorials.map((tutorial) => { const lessonCount = tutorial.sections.reduce((sum, section) => sum + section._count.lessons, 0); return <Link key={tutorial.id} href={`/learn/${tutorial.slug}`} className="group rounded-xl border border-border bg-card p-6 shadow-sm transition hover:-translate-y-0.5 hover:border-primary/40 hover:shadow-md"><div className="flex h-12 w-12 items-center justify-center rounded-lg bg-primary/10 text-primary"><Code2 className="h-6 w-6" /></div><h3 className="mt-5 text-xl font-semibold group-hover:text-primary">{tutorial.title}</h3><p className="mt-3 min-h-12 text-sm leading-6 text-muted-foreground">{tutorial.shortDescription}</p><div className="mt-5 flex flex-wrap gap-3 text-xs text-muted-foreground"><span className="flex items-center gap-1"><BookOpen className="h-4 w-4" />{lessonCount} lessons</span><span className="flex items-center gap-1"><Clock3 className="h-4 w-4" />{tutorial.estimatedDuration} min</span><span className="capitalize">{tutorial.difficulty}</span></div><span className="mt-6 inline-flex items-center text-sm font-semibold text-primary">Start tutorial <ArrowRight className="ml-2 h-4 w-4 transition-transform group-hover:translate-x-1" /></span></Link> })}</div> : <div className="rounded-xl border border-dashed border-border p-10 text-center text-muted-foreground">Published tutorials will appear here.</div>}</section></main><Footer /></div>
}
